### ISSUE TITLE
blog change on headscale post

### ISSUE THREAD

**Issue by pkkrusty** [earvingad/earvingad.github.io#2]
namespace is now user, and to register a new machine, the command now looks like:

sudo headscale --user <mynet> nodes register --key nodekey:<long hex string>

**Comment by earvingad** [comment]
Thanks! 

Changed already from `sudo headscale -n NAMESPACE nodes register --key <a-fuckin-long-key>` to `sudo headscale --user NAMESPACE nodes register --key <a-fuckin-long-key>`

NAMESPACE is just the name to replace with your headscale net name.

**Comment by pkkrusty** [comment]
Forgot to add that --key requires "nodekey:" in front of the key. Which is crazy, but wouldn't work for me until I did it.

**Comment by earvingad** [comment]
Ooh yeah, that's what I meant with `<a-fuckin-long-key>` it seems that the image I was using as example of the instructions is not being rendered. I'll replace it tomorrow for better understanding.
